name: Vue.js CI/CD Pipeline

on:
  push:
    branches:
      - 'features/**'
    paths:
      - 'cms-dashboard/**/*.js' # Target the js files inside cms-dashboard folder
      - 'cms-dashboard/**/*.vue' # Target vue files inside cms-dashboard folder
      - 'cms-dashboard/package.json' # Target package.json inside cms-dashboard folder
      - 'cms-dashboard/package-lock.json' # Target package-lock.json inside cms-dashboard folder
      - 'deployment.yml' # This can be at the root, no change here
  pull_request:
    branches:
      - 'features/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js Environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          cd cms-dashboard
          npm install
          npm install eslint stylelint # Install linting tools
